export const graduacoes = [
  // Infantil
  'Crua (Infantil)',
  'Crua ponta Cinza',
  'Crua ponta Amarela',
  'Crua ponta Laranja',
  'Crua ponta Verde',
  'Crua ponta Azul',
  'Crua ponta Roxa',
  'Crua e Cinza',
  'Crua e Laranja',
  'Crua e Verde',
  'Crua e Azul',
  'Crua e Roxa',
  'Cinza',
  'Cinza e Amarela',
  'Verde e Amarela',
  'Amarela e Azul',
  // Adulto
  'Crua',
  'Crua e Amarela',
  'Amarela',
  'Amarela e Laranja',
  'Laranja',
  'Laranja e Azul',
  'Azul',
  'Verde e Azul',
  'Verde',
  'Verde e Roxa',
  'Roxa',
  'Roxa e Marrom',
  'Marrom',
  'Marrom e Vermelha',
  'Vermelha',
  'Branca e Vermelha',
  'Branca Mor',
];

// Nomenclatura oficial de cada graduação
export const nomenclaturaGraduacao: Record<string, string> = {
  // Infantil
  'Crua (Infantil)':     'Graduação Infantil',
  'Crua ponta Cinza':    'Graduação Infantil',
  'Crua ponta Amarela':  'Graduação Infantil',
  'Crua ponta Laranja':  'Graduação Infantil',
  'Crua ponta Verde':    'Graduação Infantil',
  'Crua ponta Azul':     'Graduação Infantil',
  'Crua ponta Roxa':     'Graduação Infantil',
  'Crua e Cinza':        'Graduação Infantil',
  'Crua e Laranja':      'Graduação Infantil',
  'Crua e Verde':        'Graduação Infantil',
  'Crua e Azul':         'Graduação Infantil',
  'Crua e Roxa':         'Graduação Infantil',
  'Cinza':               'Graduação Infantil',
  'Cinza e Amarela':     'Graduação Infantil',
  'Verde e Amarela':     'Graduação Infantil',
  'Amarela e Azul':      'Graduação Infantil',
  // Adulto
  'Crua':                'Aluno',
  'Crua e Amarela':      'Aluno',
  'Amarela':             'Aluno',
  'Amarela e Laranja':   'Aluno',
  'Laranja':             'Aluno',
  'Laranja e Azul':      'Aluno',
  'Azul':                'Aluno Graduado 1º Grau',
  'Verde e Azul':        'Aluno Graduado 2º Grau',
  'Verde':               'Monitor',
  'Verde e Roxa':        'Instrutor de 1º Grau',
  'Roxa':                'Instrutor de 2º Grau',
  'Roxa e Marrom':       'Professor de 1º Grau',
  'Marrom':              'Professor de 2º Grau',
  'Marrom e Vermelha':   'Mestrando',
  'Vermelha':            'Mestre de 1º Grau',
  'Branca e Vermelha':   'Mestre de 2º Grau',
  'Branca Mor':          'Mestre Fundador',
};

export function getCordaColors(name: string): string[] {
  const map: Record<string, string[]> = {
    'Crua': ['#F5F5DC'],
    'Crua (Infantil)': ['#F5F5DC'],
    'Crua ponta Cinza': ['#F5F5DC', '#808080'],
    'Crua ponta Amarela': ['#F5F5DC', '#FFD700'],
    'Crua ponta Laranja': ['#F5F5DC', '#FF8C00'],
    'Crua ponta Verde': ['#F5F5DC', '#228B22'],
    'Crua ponta Azul': ['#F5F5DC', '#1E90FF'],
    'Crua ponta Roxa': ['#F5F5DC', '#8B008B'],
    'Crua e Cinza': ['#F5F5DC', '#808080'],
    'Crua e Laranja': ['#F5F5DC', '#FF8C00'],
    'Crua e Verde': ['#F5F5DC', '#228B22'],
    'Crua e Azul': ['#F5F5DC', '#1E90FF'],
    'Crua e Roxa': ['#F5F5DC', '#8B008B'],
    'Cinza': ['#808080'],
    'Cinza e Amarela': ['#808080', '#FFD700'],
    'Verde e Amarela': ['#228B22', '#FFD700'],
    'Amarela e Azul': ['#FFD700', '#1E90FF'],
    'Crua e Amarela': ['#F5F5DC', '#FFD700'],
    'Amarela': ['#FFD700'],
    'Amarela e Laranja': ['#FFD700', '#FF8C00'],
    'Laranja': ['#FF8C00'],
    'Laranja e Azul': ['#FF8C00', '#1E90FF'],
    'Azul': ['#1E90FF'],
    'Verde e Azul': ['#228B22', '#1E90FF'],
    'Verde': ['#228B22'],
    'Verde e Roxa': ['#228B22', '#8B008B'],
    'Roxa': ['#8B008B'],
    'Roxa e Marrom': ['#8B008B', '#8B4513'],
    'Marrom': ['#8B4513'],
    'Marrom e Vermelha': ['#8B4513', '#DC143C'],
    'Vermelha': ['#DC143C'],
    'Branca e Vermelha': ['#FFFFFF', '#DC143C'],
    'Branca Mor': ['#FFFFFF'],
  };
  return map[name] || ['#F5F5DC'];
}
